# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e108c43456f6fee330eb7516c1aed1c3153a4832ec375e73b6cbad5de7e3c64d8c1d56fb2960b45ed7d521c15d14052e4381b4ba14c1238a745f6771b82fa235

test:
  secret_key_base: 661c1102c6077eda97740f029a3e092b10e73787499c4eb9690d16188856fc8ee397c2b77a3a9dd2090a03e90b34ae1597d9b26c94c9b8399457c9071e6c19e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
